<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="chenziyang" name="文章交流测试" tests="4" failures="2" timestamp="28 Mar 2017 02:10:54 GMT" time="126.947" errors="0">
  <testcase name="sent_doc" time="77.496" classname="Documentation_and_exchange.SentDoc"/>
  <testcase name="sent_exchange" time="31.837" classname="Documentation_and_exchange.Sent_Exchange"/>
  <testcase name="document" time="5.993" classname="Documentation_and_exchange.doc_comments">
    <failure type="java.lang.AssertionError" message="expected:&amp;lt;1&amp;gt; but was:&amp;lt;0&amp;gt;">
      <![CDATA[java.lang.AssertionError: expected:<1> but was:<0>
	at Documentation_and_exchange.doc_comments.document(take_comments.java:32)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
	at java.util.concurrent.FutureTask.run(FutureTask.java:166)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
	at java.lang.Thread.run(Thread.java:722)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- document -->
  <testcase name="exchange" time="9.596" classname="Documentation_and_exchange.doc_comments">
    <failure type="java.lang.AssertionError" message="expected:&amp;lt;1&amp;gt; but was:&amp;lt;0&amp;gt;">
      <![CDATA[java.lang.AssertionError: expected:<1> but was:<0>
	at Documentation_and_exchange.doc_comments.exchange(take_comments.java:74)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
	at java.util.concurrent.FutureTask.run(FutureTask.java:166)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
	at java.lang.Thread.run(Thread.java:722)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- exchange -->
</testsuite> <!-- 文章交流测试 -->
